resources:
  - url: /local/lovelace/card-tools.js?track=true
    type: js
  - url: /local/lovelace/popup-card.js?track=true
    type: js
  - url: /local/lovelace/button-card.js?v=0.0.5
    type: module
  - url: /local/lovelace/layout-card.js?v=a313b7
    type: js
  - url: /local/lovelace/tracker-card.js?v=0.2.0
    type: js
  - url: /local/lovelace/vertical-stack-in-card.js?v=0.1.2
    type: js
  - url: /local/lovelace/slider-entity-row.js?v=0.1.0
    type: js
  - url: /local/lovelace/fold-entity-row.js?v=0.1.0
    type: js
  - url: /local/lovelace/mini-graph-card-bundle.js?v=0.3.2
    type: module
  - url: /local/lovelace/mini-media-player-bundle.js?v=1.0.4
    type: module
  - url: /local/lovelace/lovelace-swipe-navigation.js?track=true
    type: js
  - url: /local/lovelace/group-card.js?v=1.0.1
    type: js
  - url: /local/lovelace/monster-card.js?v=1
    type: js
  - url: /local/lovelace/upcoming-media-card.js?
    type: js
  - url: /local/lovelace/bar-card.js?v=1.0.0
    type: js
  - url: /local/lovelace/alarm_control_panel-card.js?track=true
    type: js
  - url: /local/lovelace/compact-custom-header.js?track=true
    type: module

cch:

views:
  - !include home.yaml
  - !include cameras.yaml
  - !include status.yaml
  - !include power.yaml
  - !include server.yaml




