# lovelace_gen
resources:

  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/group-card/group-card.js
    type: js
  - url: /community_plugin/monster-card/monster-card.js
    type: js
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/lovelace-grocy-chores-card/grocy-chores-card.js
    type: js
  - url: /community_plugin/dual-gauge-card/dual-gauge-card.js
    type: js
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module

  - url: /local/lovelace/alarm_control_panel-card.js?v=4
    type: js
  - url: /local/lovelace/layout-card.js?v=a313b7
    type: js
  - url: /local/lovelace/card-tools.js?track=true
    type: js
  - url: /local/lovelace/popup-card.js?track=true
    type: js


cch:
  header: true

views:
  - !include home.yaml
  - !include cameras.yaml
  - !include status.yaml
  - !include power.yaml
  - !include server.yaml

decluttering_templates:
  power_template:
    !include templates/power_template.yaml
  camera_template:
    !include templates/camera_template.yaml
  room_button_template:
    !include templates/room_button_template.yaml
  popup_template_powercost:
    !include templates/powercost_template.yaml
  popup_template_mediaplayer:
    !include templates/mediaplayer_template.yaml
  popup_template_first_part:
    !include templates/popup_first_part_template.yaml
  popup_template_info_part:
    !include templates/popup_info_part_template.yaml
  popup_template_cover_part:
    !include templates/popup_cover_part_template.yaml


