alias: "lights off in kitchen 1 minutes after last movement"
trigger:
  platform: state
  entity_id: binary_sensor.kitchen_sensor_25_0
  to: 'off'
  for:
    minutes: 1
action:
  service: homeassistant.turn_off
  entity_id: switch.sonoff13