alias: lights off in walk in closet 30 seconds after last movement
trigger:
  platform: state
  entity_id: binary_sensor.walkincloset_sensor_21_0
  to: 'off'
  for:
    seconds: 30
action:
  service: homeassistant.turn_off
  entity_id: switch.sonoff2